### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by eregon**
Here are some proposed updates.
Please tell me if you don't like one.

* `Minor / Upcoming Rubies` seems to be mostly not maintained Rubies now.
* I am not sure what the criteria is for "Major Rubies" but I guess TruffleRuby qualifies by its development activity, compatibility and performance.

### CODE REVIEW

**Comment by eregon** [comment]
Maybe Opal should be in Minor or Major Rubies?
It has a much better compatibility than others in the `Ruby-to` sections.

**Comment by geraldb** [comment]
@eregon  Hello, I think we have met at the Linz.rb  (looking forward to the next one in 2018 :-).  Thanks for the updates. If interested you're more than welcome to join the planet ruby github org so can edit in the browser etc. without any pull request etc - let me know and I send you an invitation (via github).     Again thanks for your great work on TruffleRuby and the updates here. Happy new year. Prosit 2018! Cheers. Keep it up.

**Comment by geraldb** [comment]
About Opal. Good point. Moved Opal to the major rubies and to make it easy to find keeping a "copy" (reference) in the Ruby-to-JavaScript category.

**Comment by eregon** [comment]
@geraldb Yes, indeed. Thanks for merging! I'd be happy to have commit rights here to edit more easily :)

**Comment by geraldb** [comment]
@eregon Great. Welcome.  Note: You will get an invitation (by email from GitHub) to join the Planet Ruby org as a member. If you accept, you can update the page in your browser  - no longer any need for a pull request - and you will show up in the people page too (if you set your preference to public - default is private; change the setting in the [github org people page](https://github.com/orgs/planetruby/people)).

**Comment by eregon** [comment]
@geraldb Thank you!

**Pull request merged**
